title: Yuan-Mao Lin, MD
description: [Department of Interventional Radiology 
The University of Texas MD Anderson Cancer Center
ORCID ID: 0000-0002-0275-9593]
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
